name: cartographer_mapper_plug
description: "Pluggable - Plug-n-Play Architecture - Mapper"
version: 0.0.1-pre.13
# pubspec_overrides.yaml

environment:
  sdk: ^3.6.0

dependencies:
  collection: any

  pluggable: 0.0.1-pre.12

dev_dependencies:
  flutter_lints: ^5.0.0

