name: _
description: "A new Flutter package project."
workspace:
  - packages/pluggable
  - packages/pluggable_flutter
  - packages/pluggable_dart_server
  - packages/plugs/di/pluggable_di_getit
  - packages/plugs/navigator/go_router_plug
  - packages/plugs/storage/expire_cache_storage_plug
  - packages/plugs/storage/in_memory_storage_plug
  - packages/plugs/storage/redis_storage_plug
  - packages/plugs/storage/object_box_storage_plug
  - packages/plugs/storage/secure_storage_plug
  - packages/plugs/mapper/cartographer_mapper_plug
  - packages/plugs/server/dart_frog_server_plug

environment:
  sdk: ^3.6.0
