name: pluggable_dart_server
description: "A Pluggable Dart Server."
# pubspec_overrides.yaml

version: 0.0.1-pre.15

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  http_methods: ^1.1.0
  http_parser: ^4.0.2
  meta: ^1.9.0
  mime: ">=1.0.4 <3.0.0"
  shelf: ^1.4.0
  shelf_hotreload: ^1.3.0
  shelf_static: ^1.1.1
  shelf_router: ^1.1.4

  pluggable: 0.0.1-pre.11

dev_dependencies:
  flutter_lints: ^5.0.0


