name: pluggable_di_getit
description: "A new Flutter package project."
version: 0.0.1
homepage: https://www.church.io
resolution: workspace

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.0.3

  pluggable:
    git:
      url: git@github.com:camrongiuliani/pluggable.git
      path: packages/core
      ref: develop

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

