name: pluggable
description: "Pluggable - Plug-n-Play Architecture"
version: 0.0.1-pre.2
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  event_bus: ^2.0.1
  use_case: ^1.1.7
  synchronized: ^3.1.0+1
  expire_cache: ^2.0.1
  http: any
  uuid: any
  collection: any

  pluggable_di_getit: 0.0.1-pre.2

  in_memory_storage_plug: 0.0.1-pre.2

  cartographer_mapper_plug: 0.0.1-pre.2

dev_dependencies:
  flutter_lints: ^5.0.0