name: object_box_storage_plug
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  stash: ^5.1.0
  stash_objectbox: ^5.1.0
  objectbox_flutter_libs: any
  uuid: any
  synchronized: ^3.1.0+1

  pluggable:
    git:
      url: git@github.com:camrongiuliani/pluggable.git
      path: packages/pluggable
      ref: develop

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0