name: dart_frog_server_plug
description: "Pluggable - Plug-n-Play Architecture"
# pubspec_overrides.yaml

version: 0.0.1-pre.15

environment:
  sdk: ^3.6.0

dependencies:
  uuid: any
  dart_frog: ^1.0.0
  dart_frog_gen: ^2.0.0

  pluggable_dart_server: 0.0.1-pre.14

dev_dependencies:
  flutter_lints: ^5.0.0
