name: pluggable_di_getit
description: "Pluggable - Plug-n-Play Architecture"
version: 0.0.1-pre.12
# pubspec_overrides.yaml

environment:
  sdk: ^3.6.0

dependencies:

  get_it: ^8.0.3

  pluggable: 0.0.1-pre.12

dev_dependencies:
  flutter_lints: ^5.0.0
