name: pluggable_di_getit
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:

  get_it: ^8.0.3

  pluggable:
    git:
      url: git@github.com:camrongiuliani/pluggable.git
      path: packages/core
      ref: develop

dev_dependencies:
  flutter_lints: ^5.0.0
