name: expire_cache_storage_plug
description: "Pluggable - Plug-n-Play Architecture"
version: 0.0.1-pre.10
# pubspec_overrides.yaml

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  synchronized: ^3.1.0+1
  expire_cache: ^2.0.1

  pluggable: 0.0.1-pre.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0